services:
  - docker

install:
- sudo docker-compose build
- sudo docker ps -a

script:
- sudo docker-compose run v2d conda run -n V2D /bin/bash -c 'cd /home/si/v2d/src/ && ./run_tests.sh'

deploy:
  provider: script
  script: bash -c '{ echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin > /dev/null 2>&1; } && docker push scopeinfinity/video2description'
  on:
    branch: docker
