name: V2D
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - c-compiler
  - make
  - keras==2.0.8
  - tensorflow==1.2.1
  - git
  - opencv
  - pip
  - python=2.7.14
  - urllib3=1.22
  - yasm
  - pip:
    - numpy==1.14.5
    - flask==0.12.2
    - keras==2.0.8
    - librosa==0.6.0
    - matplotlib==2.1.2
    - pylint==1.8.3